"""create chatroom

Revision ID: 0b589322b935
Revises: 7a116296822b
Create Date: 2019-10-26 16:19:19.456316

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0b589322b935'
down_revision = '7a116296822b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Chatroom',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('User', sa.Column('chatroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Chatroom', ['chatroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'chatroom_id')
    op.drop_table('Chatroom')
    # ### end Alembic commands ###
