"""owner model change

Revision ID: 10a8b9fd3768
Revises: 3a1eb657ace7
Create Date: 2019-11-03 01:02:23.665365

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '10a8b9fd3768'
down_revision = '3a1eb657ace7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Question', sa.Column('user_id', sa.Integer(), nullable=True)
    )
    op.drop_constraint('Question_bot_id_fkey', 'Question', type_='foreignkey')
    op.create_foreign_key(None, 'Question', 'User', ['user_id'], ['id'])
    op.drop_column('Question', 'bot_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Question',
        sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, 'Question', type_='foreignkey')
    op.create_foreign_key(
        'Question_bot_id_fkey', 'Question', 'Bot', ['bot_id'], ['id']
    )
    op.drop_column('Question', 'user_id')
    # ### end Alembic commands ###
