"""create bot

Revision ID: 18f7e2dce795
Revises: 814478712e18
Create Date: 2019-11-02 16:00:32.641477

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '18f7e2dce795'
down_revision = '814478712e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Bot',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('chatroom_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['chatroom_id'], ['Chatroom.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bot')
    # ### end Alembic commands ###
