"""empty message

Revision ID: 34540160d4c7
Revises: 2a58b5af9bdd
Create Date: 2019-10-26 20:14:33.771981

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '34540160d4c7'
down_revision = '2a58b5af9bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Message', sa.Column('chatroom_id', sa.Integer(), nullable=True)
    )
    op.add_column('Message', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Message', 'Chatroom', ['chatroom_id'], ['id'])
    op.create_foreign_key(None, 'Message', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.drop_column('Message', 'user_id')
    op.drop_column('Message', 'chatroom_id')
    # ### end Alembic commands ###
