"""asdasdsa

Revision ID: 3a1eb657ace7
Revises: 3fc3aed951eb
Create Date: 2019-11-02 18:16:27.638806

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3a1eb657ace7'
down_revision = '3fc3aed951eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chatroom', sa.Column('name', sa.String(), nullable=True))
    op.add_column(
        'Chatroom', sa.Column('thumbnail', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Chatroom', 'thumbnail')
    op.drop_column('Chatroom', 'name')
    # ### end Alembic commands ###
