"""owner chatroom

Revision ID: 8cfc03dea077
Revises: 0b589322b935
Create Date: 2019-10-26 16:34:16.060859

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8cfc03dea077'
down_revision = '0b589322b935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Chatroom', sa.Column('owner_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, 'Chatroom', 'User', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chatroom', type_='foreignkey')
    op.drop_column('Chatroom', 'owner_id')
    # ### end Alembic commands ###
