"""message update

Revision ID: 9c922379e840
Revises: 10a8b9fd3768
Create Date: 2019-11-08 20:11:10.913668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9c922379e840'
down_revision = '10a8b9fd3768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Message', sa.Column('question_id', sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, 'Message', 'Question', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.drop_column('Message', 'question_id')
    # ### end Alembic commands ###
