"""remove message

Revision ID: bcf04e3aec4f
Revises: 9c922379e840
Create Date: 2019-11-08 20:13:40.784651

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bcf04e3aec4f'
down_revision = '9c922379e840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'Message_question_id_fkey', 'Message', type_='foreignkey'
    )
    op.drop_column('Message', 'question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Message',
        sa.Column(
            'question_id', sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        'Message_question_id_fkey',
        'Message',
        'Question',
        ['question_id'],
        ['id'],
    )
    # ### end Alembic commands ###
