"""create question

Revision ID: c5861c12f746
Revises: 18f7e2dce795
Create Date: 2019-11-02 16:11:56.148162

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c5861c12f746'
down_revision = '18f7e2dce795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
