"""empty message

Revision ID: f90185cbc4e1
Revises: 0ef5c646deca
Create Date: 2019-10-26 16:42:51.875669

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f90185cbc4e1'
down_revision = '0ef5c646deca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chatroom', sa.Column('url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Chatroom', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chatroom', type_='unique')
    op.drop_column('Chatroom', 'url')
    # ### end Alembic commands ###
